### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by Kyokyonos** [Steveice10/citrus#11]
Hello,

Is there any chance this library will include documentation (or brief descriptions) for the many header file functions (and 3DS hardware-specific terminology)? Or maybe I'm overlooking it or maybe a tutorial can be found? Perhaps I'm missing some fundamentals (I have never used OpenGL)? I feel like the only thing stopping me from making something useful/pretty is actually knowing what everything does-- I consider myself a decent programmer (have taken an embedded systems class-- microcontroller features/peripherals are heavily documented) but really have no idea what functions are doing like "gpu::flushCommands()" (i.e. what commands?) or "gpu::swapBuffers()" (i.e. what does swapping buffers do?)  or "gpu::setViewport()" (i.e. what's does viewport mean in this context?).  

I mean, I recently got an onscreen keyboard working nicely with citrus, but I don't even know how to do things clear the buffer in the bottom screen when I'm finished using it (using clear() just causes to flash/blink rapidly). I've been using trial and error to try to understand them ... but how can I understand the functions better? (Unless you don't mind me asking you how to do every little thing I want to do ;P)

Thanks!

**Comment by Steveice10** [comment]
At the moment I don't plan on writing much documentation for this, sorry. This library was created more for personal use than anything else. If you're looking for a well-documented 3DS library, I would recommend just using ctrulib.

**Comment by bennyman123abc** [comment]
I could help with documentation when I learn this library myself. I personally like Citrus better than ctrulib for reasons such as easier usability and the fact it's supported by 3ds_monty (A 3DS Python runtime that works almost as well as straight compiled C or C++)

**Comment by Steveice10** [comment]
Just so you know, this issue is 2 years old, and this library is no longer being worked on at all.

**Comment by bennyman123abc** [comment]
Wow. I honestly wouldn't have guessed due to the fact it's still supported in some rare cases. You still looking for docs tho?
