### ISSUE TITLE
Unable to compile

### ISSUE THREAD

**Issue by Shinigati** [Steveice10/citrus#15]
Sorry i feel this isn't the best place to ask but i was sure i had everything setup properly but i get this error while compiling: c:/devkitpro/devkitarm/bin/../lib/gcc/arm-none-eabi/5.3.0/../../../../arm-none-eabi/bin/ld.exe: cannot find -lcitrus
collect2.exe: error: ld returned 1 exit status
make: *** [output/GameYob.elf] Error 1

<style type="text/css" scoped>

</style>

<img src="http://oi68.tinypic.com/111igkg.jpg" alt="Photo of the Remarkables mountain range in Queenstown, New Zealand." class="GeneratedImage">

**Comment by Steveice10** [comment]
Did you install citrus to your environment?
