### ISSUE TITLE
Problems compiling from a clean source pull

### ISSUE THREAD

**Issue by ksanislo** [Steveice10/citrus#16]
It looks like a few entries aren't getting built into the ./build/source/citrus/*.h files anymore... I manually put them in and things work again, but this will break for anyone starting from scratch that doesn't know how to define these.

`
build/source/citrus/gput.o
source/citrus/gput.cpp: In function 'bool ctr::gput::init()':
source/citrus/gput.cpp:39:65: error: 'citrus_default_shader_shbin_size' was not declared in this scope
     gpu::loadShader(defaultShader, citrus_default_shader_shbin, citrus_default_shader_shbin_size);
                                                                 ^
source/citrus/gput.cpp:47:33: error: 'citrus_default_font_bin_size' was not declared in this scope
     void* gpuFont = gpu::galloc(citrus_default_font_bin_size);
                                 ^
buildtools/make_base:277: recipe for target 'build/source/citrus/gput.o' failed
make: *** [build/source/citrus/gput.o] Error 1
`

**Comment by Steveice10** [comment]
Should be fixed by https://github.com/Steveice10/citrus/commit/fd5c846b42f1872079018aece1499afdc79a4ac8
