### ISSUE TITLE
Trouble with latest ctrulib

### ISSUE THREAD

**Issue by d0k3** [Steveice10/citrus#22]
I get this, trying to compile CTRXplorer with citrus:

c:/devkitPro/citrus/lib\libcitrus.a(gpu.o): In function `ctr::gpu::safeWait(GSPGPU_Event)':
C:\GitHub\citrus/source/citrus/gpu.cpp:516: undefined reference to `gspEvents'
collect2.exe: error: ld returned 1 exit status
make: *** [output/CTRXplorer.elf] Error 1

gspEvents is not in a visible interface (anymore), so that's where that problem most likely comes from:
https://github.com/smealum/ctrulib/blob/master/libctru/source/services/gspgpu.c#L18

**Comment by Steveice10** [comment]
Fixed.
