### ISSUE TITLE
Update for latest devkitpro

### ISSUE THREAD

**Issue by urherenow** [Steveice10/citrus#23]
latest devkitPro and Ctrulib (as of today) yields:

source/citrus/core.cpp:30:9: error: invalid conversion from 'ssize_t (*)(_reent*, int, const char*, size_t) {aka int (*)(_reent*, int, const char*, unsigned int)}' to 'ssize_t (*)(_reent*, void*, const char*, size_t) {aka int (*)(_reent*, void*, const char*, unsigned int)}' [-fpermissive]
         };
         ^
make: *** [build/source/citrus/core.o] Error 1

**Comment by Steveice10** [comment]
Fixed.
