### ISSUE TITLE
/bin/sh: line 4: zip: command not found

### ISSUE THREAD

**Issue by FayneAldan** [Steveice10/citrus#4]
The included make_base file uses the zip command to compress the output files into one archive. However, MINGW32 doesn't include the zip command by default.

**Comment by FayneAldan** [comment]
In addition, running `make` puts the files into the archive in an odd format:
- GameYob.zip
  - home\steven\Desktop\programming\3DS\Apps\GameYob\output\
    - GameYob.3ds
    - GameYob.cia
    - GameYob.elf
  - 3ds\GameYob\
    - GameYob.3dsx
    - GameYob.smdh
I doubt this was intentional, as the download for the 3DSHomebrewTemplate repo has the 3ds, cia, and elf files in the main folder of the ZIP archive. That file tree above is even from all your recent GameYob distributions.

**Comment by Steveice10** [comment]
ZIP structure should be fixed now, and I've updated my latest releases as well.

As for zip, all I can say is get the zip command. I can't help it if your environment doesn't include it by default.

**Comment by FayneAldan** [comment]
Well, you could at least leave a note somewhere saying you'll have to download `zip` if you're using MINGW32. It can be downloaded [here](http://sourceforge.net/projects/mingw/files/MSYS/Extension/zip/zip-3.0-1/zip-3.0-1-msys-1.0.14-bin.tar.lzma/download).

**Comment by Steveice10** [comment]
With that logic, I'd have to include a note for every possible OS and setup that might not have zip.

**Comment by FayneAldan** [comment]
True that...
