### ISSUE TITLE
can't compile with current version of ctrulib great-refactor branch

### ISSUE THREAD

**Issue by neumaennl** [Steveice10/citrus#7]
neumaennl@Chakra:~/git/citrus$ git pull
Already up-to-date.
neumaennl@Chakra:~/git/citrus$ make clean
clean ...
neumaennl@Chakra:~/git/citrus$ make
citrus_default_font.bin
citrus_default_shader.pica
wifi.cpp
arm-none-eabi-g++ -MMD -MP -MF /home/neumaennl/git/citrus/build/wifi.d -g -Wall -Wno-strict-aliasing -O3 -mword-relocations -fomit-frame-pointer -ffast-math -march=armv6k -mtune=mpcore -mfloat-abi=hard -I/home/neumaennl/git/citrus/include -I/opt/devkitPro/libctru/include -I/home/neumaennl/git/citrus/build -DARM11 -D_3DS -DLIBKHAX_AS_LIB -fno-rtti -fno-exceptions -std=gnu++11 -c /home/neumaennl/git/citrus/source/citrus/wifi.cpp -o wifi.o
/home/neumaennl/git/citrus/source/citrus/wifi.cpp: In function 'void ctr::wifi::waitForInternet()':
/home/neumaennl/git/citrus/source/citrus/wifi.cpp:57:102: error: 'ACU_WaitInternetConnection' was not declared in this scope
     ctr::err::parse(ctr::err::SOURCE_WIFI_WAIT_INTERNET_CONNECTION, (u32) ACU_WaitInternetConnection());
                                                                                                      ^
/opt/devkitPro/devkitARM/base_rules:79: recipe for target 'wifi.o' failed
make[1]: *** [wifi.o] Error 1
Makefile:116: recipe for target 'build' failed
make: *** [build] Error 2
neumaennl@Chakra:~/git/citrus$

**Comment by Steveice10** [comment]
I had the citrus changes ready, but was waiting for my FS changes to be pulled in to ctrulib. Forgot to push my changes when it was pulled, though. Should be fixed now.

**Comment by neumaennl** [comment]
still having problems:

http://pastebin.com/gNgzkKj0

**Comment by Steveice10** [comment]
You'll need to make some manual changes to libkhax, as it's a submodule. It still hasn't been updated to great-refactor, but it's only some minor changes.

**Comment by Kyokyonos** [comment]
I was able to get it to build after looking over the referenced ctrulib header files-- a few things seemed to have been renamed in the great-refactor branch. Not sure if this is right, but for anyone else with this exact problem, the minor changes in source/libkhax/khaxinit.cpp include:

```u32 physical = osConvertVirtToPhys(addr);```->
```u32 physical = osConvertVirtToPhys(&addr);```

```if (Result error = APT_CheckNew3DS(nullptr, &isNew3DS))```->
```if (Result error = APT_CheckNew3DS(&isNew3DS))```

```GSPGPU_FlushDataCache(nullptr, static_cast<u8 *>(const_cast<void *>(src)), size);```->
```GSPGPU_FlushDataCache(static_cast<u8 *>(const_cast<void *>(src)), size);```

```GSPGPU_InvalidateDataCache(nullptr, static_cast<u8 *>(dest), size);```->
```GSPGPU_InvalidateDataCache(static_cast<u8 *>(dest), size);```

```GX_SetTextureCopy(nullptr, static_cast<u32 *>(const_cast<void *>(src)), 0,
		static_cast<u32 *>(dest), 0, size, 8))```->
```GX_TextureCopy(static_cast<u32 *>(const_cast<void *>(src)), 0,
		static_cast<u32 *>(dest), 0, size, 8))```

**Comment by Steveice10** [comment]
That's mostly correct, except the first change is wrong. Changing it to a pointer to addr is wrong, you should either change the parameter to the pointer addr came from or cast addr itself to a pointer type.
